Machine Learning: Algoritmo KNN

## Intro Teoría KNN

* Usado para predecir un nuevo valor basandose en en función de la distancia entre los datos cercanos (K puntos).
* Cuánto más numero de datos iguales más problable que el resultado sea similar a las caracteristicas de  nuestro valor y --> DUDA
* Calcula da distancia entre puntos cercanos a nuestro dato. Tomamos muestras de K-vecinos distintos, se escoge una métrica de distancia para determinar los K-vecinos. (SEÑALAR METRICAS duda)
* Utilizado para problemos supervisados de Clasificación y Regresión aunque es más utilizado en clasificación.

         - Que son problemas supervisados? Significa que ya tenemos la columna con resultados de lo que queremos predecir, usamos datos ya existentes para crear nuevos resultados utilizando distintos algoritmos.
         Escogemos el tipo de algoritmo según los tipos de datos que tengamos, cómo se relacionen entre ellos y qué modelo se ajusta más a lo que uqremos predecir.


* Cómo trabaja el algoritmo KNN? DUDA-> REVISAR CON ADAM PUNTO 4

        1. **Selección del valor de K:** Se elige un valor para K: K representa el número de puntos de datos más cercanos que se considerarán para clasificar o predecir el nuevo punto de datos. 
         Un valor pequeño puede llevar a un modelo más ruidoso y sensible a valores atípicos (outliers), mientras que un valor elevado puede facilitar la toma de decisión.
        2. **Medición de distancia:** Se utiliza una métrica para calcular la distancia entre el punto de datos a clasificar o predecir y los demás puntos de datos en el conjunto de entrenamiento.
        3. **Identificación de los K vecinos más cercanos:** Se seleccionan los K puntos de datos más cercanos (en función de la medición seleccionada).
        4. **Predicción:** Si se trata de un problema de clasificación, el nuevo punto se clasifica en la clase más frecuente entre los K vecinos más cercanos. Si se trata de un problema de regresión, el valor objetivo para el nuevo punto se calcula como la media o la mediana de los valores de los K vecinos más próximos.
*  Definir Clasificacin y Regresión. --> DUDA
* Ejemplos:

        - Clasificar el riesgo crediticio (moroso / no moroso) de una persona basado en infividuos similares.

        - Predecir cuánto dinero gasta un cliente potencial en nuestro negocio en base a los 5 clientes más similares a él y promediar sus gastos para hacer la predicción.

### Métricas de distancia

* Son funcoines utilizadas para medir la proximidad o similitus entre dos puntos de datos en un modelo KNN.

# **EDA**
> * Datos sobre: busca analizar e investigar los conjuntos de datos de los que disponen y resumir sus principales características, visualización de datos para ver su comportamiento y distribución de los mismos.
> * Objetivo: Determinar las mejores variables enfocando el análisis a buscar los vinos de calidad "buena" o "mala".
> * Enfoque: Crear predicciones favorables utilizando Machine Learning KNN.

## Paso 0: **Imports & Read data**

> (1) **Importar librerías necesarias**  
> - pandas para cargar nuestros datos  
> - matplotlib y seaborn para graficos  
  
> (2) **Crear el DataFrame**  
> (2.1) **Definición del problema e información del conjunto de datos**

### (1) **Importas para EDA:**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px # Graficos tridimensionales
import seaborn as sns

### (2) **Definición de la información del conjunto de datos**

* **Creamos el DataFrame:**

In [43]:
df = pd.read_csv("https://raw.githubusercontent.com/4GeeksAcademy/k-nearest-neighbors-project-tutorial/refs/heads/main/winequality-red.csv", sep=";")
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [44]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

OBSERVACIONES DE .info():    

    - La 1ª columna "#" indica el índex de las variables y la 2ª su nombre/indicador.
    - La 3ª columna cuenta los valores no nulos, dónde sí tenemos data en cada fila y el restante en comparación al total de filas serán las filas que contienen valores nulos. ¿Hay valores NaN? ¿Dónde?
    - La 4ª columna nos dice el tipo de dato que contienen las variables, numéricos o objeto.
    - Por último tenemos un recuento de los tipo de variable y cuánto ocupa en la memoria el total del df.

In [45]:
df.describe().T.round(2).sort_values("mean", ascending=False)

                       count   mean    std   min    25%    50%    75%     max
total sulfur dioxide  1599.0  46.47  32.90  6.00  22.00  38.00  62.00  289.00
free sulfur dioxide   1599.0  15.87  10.46  1.00   7.00  14.00  21.00   72.00
alcohol               1599.0  10.42   1.07  8.40   9.50  10.20  11.10   14.90
fixed acidity         1599.0   8.32   1.74  4.60   7.10   7.90   9.20   15.90
quality               1599.0   5.64   0.81  3.00   5.00   6.00   6.00    8.00
pH                    1599.0   3.31   0.15  2.74   3.21   3.31   3.40    4.01
residual sugar        1599.0   2.54   1.41  0.90   1.90   2.20   2.60   15.50
density               1599.0   1.00   0.00  0.99   1.00   1.00   1.00    1.00
sulphates             1599.0   0.66   0.17  0.33   0.55   0.62   0.73    2.00
volatile acidity      1599.0   0.53   0.18  0.12   0.39   0.52   0.64    1.58
citric acid           1599.0   0.27   0.19  0.00   0.09   0.26   0.42    1.00
chlorides             1599.0   0.09   0.05  0.01   0.07   0.08   0.09    0.61

### (2) **Descripción de la data inicial:** 

- ¿Qué indican las filas del df?
- Las columnas son los artibutos / características que aporta df de cada fila ¿Qué indican las columnas?

**Observaciones:** COMPLETAR
  * ¿Qué representa una fila? ¿Un cliente, una compra, una medición de sensor…?
  * ¿Qué columnas solo se conocen después del resultado? (posible leakage)
  * ¿Qué queremos predecir o explicar? → **target** (columna objetivo).

**Conclusiones:**

Las variables realmente relevantes:
    
        - col_a,

* Observaciones de la Distribución:  
     - ¿Se observa alta dispersión y presencia de valores extremos?    

* Observaciones de los Valores faltantes:  
     - ¿En qué columnas predominan? ¿Parecen outliers?

In [46]:
col_numericas = df.select_dtypes(include=['number']).columns.tolist()
col_categoricas = df.select_dtypes(include=['object']).columns.tolist()

print("Columnas numericas:", col_numericas)
print("Columnas categoricas:", col_categoricas)

Columnas numericas: ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality']
Columnas categoricas: []

COLUMNAS Y CARACTERÍSTICAS DE LAS VARIABLES

**1. NUMÉRICAS:**

> * Medicas:  
    - 
> * Persona:  
    - 

**2. CATEGÓRICAS**  

* **Variable target** 
> ``Outcome``,

* **Variables predictoras:**

* **Variable target:**

In [47]:
df["quality"].unique()

array([5, 6, 7, 4, 8, 3])

* **Filtrado de la columna target por rangos:**
        - Nueva columna 'range_quality' que contiene valor tipo object-string.
        - Los rangos son: 'buena' =  y 'mala'

In [48]:
df["range_quality"] = df["quality"].apply(lambda x: "buena" if x >= 6 else "mala") # Para usar en ML
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,range_quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,mala
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,mala
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,mala
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,buena
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,mala

> Vemos que en la columna Quality tenemos un rango de calidades que va del 3 al 8.

Ejemplo:

 "[Link data original]('https:url')"

* **Resumen estadístico del df original:**

* **Resumen estadístico del df ordenado por promedio:**

## Paso **1: Limpieza de datos**

Recuerda: ¿Son todas las características imprescindibles para realizar una predicción? Trataremos de hacer es una eliminación controlada de aquellas variables que estamos seguros de que el algoritmo no va a utilizarlas en el proceso predictivo.

> (1) **Valores NaNs**

### (1) **Valores NaNs**

¿Hay valores NaN? ¿Dónde? ¿Representarían información importante para el análisis?

In [49]:
df.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
range_quality           0
dtype: int64

In [50]:
df_nas = df.loc[df["name"].isna()]

KeyError: 'name'

**Conclusion NaS:**¿Qué hago con ellos? ¿Decido rellenarlos? ¿Eliminar filas o mantenerlas?

### (2) **Valores duplicados**

In [ ]:
df.duplicated().sum()

In [ ]:
df.sample(5, random_state=0)

In [ ]:
df.nunique()

In [ ]:
# initial_rows = df.shape[0]
# df = df.drop_duplicates()
# print(f"✅ Duplicados eliminados: {initial_rows - df.shape[0]} filas borradas.")

### (3) **Valores a 0**

In [ ]:
(df == 0).sum()

In [ ]:
df.loc[(df == 0).any(axis=1)] # Ver filas que contienen almenos un 0

In [ ]:
# df_availability_0 = df.loc[(df["availability_365"]==0)]
# # df_numreviews_0 = df[df['number_of_reviews'] == 0] 
# # df_numreviews_0.count(), df_numreviews_0.count()
# f'El número de apartamentos con 0 disponibilidad es {df_availability_0.shape[0]} y los que no contienen reviews es {df_numreviews_0.shape[0]}.'

**Observaciones de valores a 0:**


> * En las columnas con más valores a 0 son ....Para el análisis podríamos pasarlos a valores NaN sin necesidad de eliminar las columnas pero no/si las utilizaría para el ML ya que representan .... sobre la data en valores nulos.  
>  
> * Decido eliminar las filas que contienen valores zero.... la columna que adquiere/ adquieren mayor importancia son ...

* **Limpieza de filas con valores nulos:**

In [ ]:
df = df.drop(df[(df['BMI'] == 0) & (df['Glucose'] == 0) & (df['BloodPressure'] == 0)].index)

* **Limpieza de columnas con valores nulos:**

In [ ]:
df = df.drop(['SkinThickness', 'Insulin'], axis=1)

* **Características del Nuevo df:**

In [ ]:
df.shape

In [ ]:
df.head(5)

**OBSERVACIONES DESPUES DE LA LIMPIEZA DE DATOS:** Nos quedamos con ... columnas y ... filas.

* **Columnas con mayor importancia:**
> 
 * **Nueva variable target** 
> * ``Si hay nueva``,

## Paso 2: **Análisis de Variables**

> (1) **Análisis de Variables**  
> (1.1) **Categórica: Variable target**  
> (1.2) **Numéricas** 
> Análisis Multivariante  
> (2) **Correlaciones**

Columnas numericas: ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality']
Columnas categoricas: []

## Paso 3: Análisis de variables

> (1) **Descripción de columnas utilizadas para el análisis**   
> (2) **Análisis de Variables Numéricas:**  
> (3) **Análisis de Variables Categóricas,** *tipo de variable que puede tomar uno de un número limitado de categorías o grupo, ninguno de los valores es inherentemente "mayor" o "mejor" que los demás (colores) pero pueden también representarse mediante números finitos (yellow=0, blue=1, pink=2).*

> Tipos de análisis: Univariante & Multivariante  

        - Univariante: Una **variable univariante** es un término estadístico que se emplea para referenciar un conjunto de observaciones de un atributo (obervaciones=características, atributo =columna).  

         - Univariante: 


>   - Según tipo de variable:

1. Numérica - Continua
2. Numérica - Discreta
3. Categórica - Nominal
4. Categórica -

### (1) **Descripción de columnas utilizadas para el análisis:**

### (2) **Análisis de Variables Numéricas:**

     -Boxplot: Dentro del rectangulo, dos particiones: cuartil 25% (Q2) y cuartil 50% (Q3)

In [ ]:
df_analisis[df_analisis['number_of_reviews']<60].boxplot(column=['number_of_reviews']) #

In [ ]:
#Calcuo outliers: 
# FORMULA cálculo quantile 3:  Q3 + 1.5*IQR --> 24 + 1.5(24-1) =~ 60

df_analisis.boxplot(column=['number_of_reviews'])
plt.ylim(0,60) # filtro altura de outliers por rango
# plt.ylim(top=60) # corte del gráfico en 60
plt.show()

### (3) **Análisis de Variables Categóricas:**

# **ML**

A los algoritmos de ML le gustan los vectores :)

Para que cada fila sea un vector no debe tener valores nulos y cada celda debe ser un numero y no un texto o fecha u otra cosa que no sea un numero. Entonces deberemos:

1. Eliminar o imputar nulos en el EDA (Paso previo)
2. Eliminar o transformar en numeros las celdas que no son numeros en el EDA. (Paso previo)
3. **Con los algoritmos KNN..... (arboles: no es necesario normalizar la data, además en este proyecto no tenemos ninguna varibale categórica. Sin embargo, en algoritmos como knn, regresion y redes neuronales es bueno aplicar transformaciones de normalizacion a las columnas numericas.)**

## Paso 0: **Imports ML**
> - split para modelado       
>         from sklearn.model_selection import train_test_split, GridSearchCV
> - sklearn para realizar el ML:  
>    . sklearn.model_selectio para train_test_split  
> . sklearn.preprocessing para StandardScaler, MinMaxScaler  
> . sklearn.preprocessing para LabelEncoder, OneHotEncoder, OrdinalEncoder  
> .sklearn.feature_selection para f_classif, SelectKBest  
>  * ML:  .pickle y .json para guardar los modelos

In [ ]:
# Modelado
from sklearn.neighbors import KNeighborsClassifier # El corazón del modelo
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV

# Métricas de Clasificación
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix, classification_report

# Utilidades
from scipy.stats import randint
import warnings
warnings.filterwarnings('ignore')

https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

https://scikit-learn.org/stable/api/sklearn.metrics.html

DUDA: NECESITO ESCALADO? ENCODING? CUAL ELEGIR?

## Paso 1: **Lectura de los datos procesados**

In [ ]:
df.to_csv("../data/processed/k-nearest-winequality-red.csv", index=False)
df = pd.read_csv('../data/processed/k-nearest-winequality-red.csv')
pd.DataFrame(df)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,range_quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,mala
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,mala
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,mala
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,buena
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,mala
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,mala
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,buena
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,buena
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,mala
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6,buena

## PASO 2: **Split data**


 




Definimos cual es la columna a predecir y que columnas utilizaremos como predictoras.

(Esta separacion deberia hacerse al principio antes de la imputacion de nulos y la transformacion de los datos pero por simplicidad haremos esta pequeña trampa de hacerlo luego.)

In [62]:
df["y"] = df["quality"].apply(lambda x: "buena" if x >= 2 else "mala")
X = df.drop(["y","quality","range_quality"],axis=1)
y = df["y"]

In [63]:
X

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0

In [ ]:
# DUDA--> NORMALIZACION DE LA DATA
from sklearn.preprocessing import StandardScaler
X[col_numericas] = sklearn.preprocessing.StandardScaler().fit_transform(X[col_numericas])

In [ ]:
# scaler = StandardScaler()
# X_train_scaled = scaler.fit_transform(X_train)
# X_val_scaled = scaler.transform(X_val)
# X_test_scaled = scaler.transform(X_test)
# print("X_train_scaled:", X_train_scaled.shape)
# print("X_val_scaled:", X_val_scaled.shape)
# print("X_test_scaled:", X_test_scaled.shape)

# scaler = StandardScaler()

# # Ajustamos SOLO con el train
# X_train_scaled = scaler.fit_transform(X_train)

# # Transformamos el test
# X_test_scaled = scaler.transform(X_test)

In [59]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)


## Paso 3: **Modelado y entrenamiento** 
> * El árbol de decisión muestra qué variables están siendo utilizadas para separar las clases primero. La variable en la primera división es la que tiene mayor poder de separación entre personas con y sin diabetes en este dataset.
> * Hiperparametrización 
dt_classifier_model = DecisionTreeClassifier(random_state=42, max_depth=3)
dt_classifier_model.fit(X_train, y_train)

In [ ]:
knn_model = KNeighborsClassifier()

knn_model.fit(X_train, y_train)

KNeighborsClassifier()

**Observaciones:**

> *

## Paso 4: **Predicción**

### (1) **DataFrame comparativo entre las predicciones y la data de testeo**

* Usamos X_test para predecir
* Análisis Overfitting con x_train vs X_test

In [ ]:
y_pred_test = knn_model.predict(X_test)
y_pred_test

In [ ]:
# df de comparación resultados df test con la predición
pred_vs_real = pd.DataFrame()
pred_vs_real["y_test"] = y_test
pred_vs_real["predicciones"] = y_pred_test
pred_vs_real

In [ ]:
y_pred_train = knn_model.predict(X_train)
y_pred_train

In [ ]:
# df de comparación resultados df entrenamiento con la predición
pred_vs_real = pd.DataFrame()
pred_vs_real["y_train"] = y_train
pred_vs_real["predicciones"] = y_pred_train
pred_vs_real

In [ ]:
# Comparación de eficiencia entre las predicciones del df test y el df de entrenamiento
accuracy = {'Accuracy Test': accuracy_score(y_test, y_pred_test),
            'Accuracy Train': accuracy_score(y_train, y_pred_train)}
accuracy

### (2) **Moda como predictor base**

Aqui utilizaremos los predictores Dummy de sklearn que nos permiten exactamente eso tener una base contra la cual comparar nuestros resultados


predictor_mode = DummyClassifier(strategy='most_frequent')
predictor_mode.fit(X_train, y_train);

predicciones_mode = predictor_mode.predict(X_test)

accuracy_mode = accuracy_score(y_test, predicciones_mode)
print("Accuracy base:", accuracy_mode)

## Paso 5: **Hiperparametrización y métricas**

### (1) **Hiperparametrización**

In [ ]:
hiper_params = {'n_neighbors': 27,
                'weights': ['uniform', 'distance'],
                'p': [1, 2]}

### (2) **Métricas del modelo de Clasificación**

* **Accuracy** (exactitud)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy= accuracy_score(y_test, y_pred,normalize=False)
print("Accuracy Arbol:", accuracy)


* **Precision**

In [ ]:
print(precision_score(y_test, y_pred,average='micro')) # duda revisar


* **Recall** (sensibilidad)


* **F1 score**

* **GridScearchCV: Overfitting**

https://4geeks.com/es/lesson/optimizacion-de-hiperparametros-del-modelo

In [ ]:
# revisa hiperparam. K[]
hyperparams = {"K": [0.001, 0.01, 0.1, 1, 10, 100, 1000],"metrics": ["", None],"weights": [""],"algorithm":[""]}
grid = GridSearchCV(df, hyperparams, scoring = "accuracy", cv = 5)
print(grid)

* **Random SeacrhCV**

In [ ]:
random_search = RandomizedSearchCV(estimator=knn_model, param_distributions=hiper_params, n_iter=50, cv=5, scoring='accuracy', random_state=42, n_jobs=-1)

random_search.fit(X_train, y_train)
random_search.best_params_

In [ ]:
random_search.best_score_

In [ ]:
best_knn = random_search.best_estimator_
y_pred = best_knn.predict(X_test)
test_accuracy = accuracy_score(y_test, y_pred)
test_accuracy


### (2) **Matriz de confusión**

Matriz de confusión: Esta matriz muestra cuántos valores se clasificaron correctamente o incorrectamente. Los valores diagonales representan aciertos y los otros representan errores.

Las metricas que obtengamos de este resultado seran las que comuniquemos en nuestro reporte final para decir que tan bien funciona el modelo predictivo que hemos seleccionado


DUDA::: Utilizando la caja negra predictora seleccionada y creando reporte final con el conjunto de prueba (X_test,y_test)

In [ ]:
matrix = confusion_matrix(y_test, y_pred)
print("Accuracy por clase:", matrix.diagonal()/matrix.sum(axis=1))
confussion_matrix = confusion_matrix(y_test, y_pred)
sns.heatmap(confussion_matrix, annot=True, fmt='g')
plt.xlabel('Predicho')
plt.ylabel('Real');

**OBSERVACIONES:**

>

### (2.1) **Matriz de confusión para la predicción en base a la moda**

In [ ]:
matrix_moda = confusion_matrix(y_test, predicciones_mode)
print("Accuracy por clase:", matrix_moda.diagonal()/matrix_moda.sum(axis=1))
confussion_matrix_mode = confusion_matrix(y_test, y_pred)
sns.heatmap(confussion_matrix_mode, annot=True, fmt='g')
plt.xlabel('Predicho')
plt.ylabel('Real');


**OBSERVACIONES DE LAS MATRICES DE CONFUSIÓN:**

>Accuracy / Reporte de clasificación--- DUDA

> Este resultado es bueno o es malo?
> 
> Como saber si mi prediccion es buena o mala?
> 
> - 90% de Accuracy (u otra metrica) es bueno?
> - 30% de Accuracy (u otra metrica) es malo?
> 
> Todo es relativo, cual es el accuracy actual en el negocio? Que se utiliza actualmente para hacer la prediccion? Podemos comparar contra eso? Lo mejoramos o no?
> 
> Lo mas recomendado es establecer una base, si el negocio ya la tiene podemos empezar por alli si no podemos utilizar la media o la moda como predictor base dependiendo si la variable a predecir es numerica o categorica respectivamente.

## Paso 6: **Guardado del modelo**

In [ ]:
with open('../../models/iris-decision-tree-classifier.pkl', 'wb') as file:
    pickle.dump(dt_classifier_model, file)